[websites]
dangerzone-websites ansible_host=192.168.69.69 ansible_user=vagrant

[websites:vars]
ansible_ssh_private_key_file=../.vagrant/machines/default/virtualbox/private_key
ansible_python_interpreter=/usr/bin/python3